import JSZip from 'jszip';
import { storage } from './storage';
import { SUPPORTED_LANGUAGES, type SupportedLanguage } from '@shared/schema';

const LANG_NAMES: Record<string, string> = {
  en: 'English', ar: 'Arabic', tr: 'Turkish', fr: 'French',
  ru: 'Russian', fa: 'Farsi', zh: 'Chinese', hi: 'Hindi',
  es: 'Spanish', id: 'Indonesian',
};

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function renderLangPage(
  lang: string,
  tenant: any,
  theme: any,
  sectionsList: any[],
  faqList: any[],
  testimonialsList: any[],
  seo: any,
): string {
  const langName = LANG_NAMES[lang] || lang;
  const metaTitle = seo?.metaTitleByLang?.[lang] || tenant.universityName;
  const metaDesc = seo?.metaDescriptionByLang?.[lang] || '';
  const isRTL = lang === 'ar' || lang === 'fa';
  const dir = isRTL ? 'rtl' : 'ltr';
  const primaryColor = theme?.primaryColor || '#2563eb';

  const sectionHtml = sectionsList
    .filter(s => s.isEnabled)
    .sort((a, b) => (a.displayOrder ?? 0) - (b.displayOrder ?? 0))
    .map(s => {
      const c = s.contentByLang?.[lang] || s.contentByLang?.['en'] || {};
      return `
      <section class="section" id="${escapeHtml(s.sectionKey)}">
        <h2>${escapeHtml(c.title || s.sectionKey)}</h2>
        ${c.subtitle ? `<p class="subtitle">${escapeHtml(c.subtitle)}</p>` : ''}
        ${c.body ? `<div class="body">${escapeHtml(c.body)}</div>` : ''}
        ${c.ctaLabel ? `<a class="cta" href="${escapeHtml(c.ctaUrl || '#')}">${escapeHtml(c.ctaLabel)}</a>` : ''}
      </section>`;
    }).join('\n');

  const faqHtml = faqList.filter(f => f.isEnabled).map(f => {
    const q = f.questionByLang?.[lang] || f.questionByLang?.['en'] || '';
    const a = f.answerByLang?.[lang] || f.answerByLang?.['en'] || '';
    return `<dt>${escapeHtml(q)}</dt><dd>${escapeHtml(a)}</dd>`;
  }).join('\n');

  const testimonialHtml = testimonialsList.filter(t => t.isEnabled).map(t => {
    const content = t.contentByLang?.[lang] || t.contentByLang?.['en'] || '';
    return `
      <blockquote>
        <p>${escapeHtml(content)}</p>
        <footer>— ${escapeHtml(t.studentName)}${t.country ? `, ${escapeHtml(t.country)}` : ''}</footer>
      </blockquote>`;
  }).join('\n');

  return `<!DOCTYPE html>
<html lang="${lang}" dir="${dir}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(metaTitle)}</title>
  ${metaDesc ? `<meta name="description" content="${escapeHtml(metaDesc)}">` : ''}
  <style>
    :root { --primary: ${primaryColor}; }
    body { font-family: system-ui, sans-serif; margin: 0; padding: 0; color: #1f2937; direction: ${dir}; }
    header { background: var(--primary); color: #fff; padding: 1.5rem 2rem; }
    header h1 { margin: 0; font-size: 1.5rem; }
    main { max-width: 900px; margin: 0 auto; padding: 2rem; }
    .section { margin-bottom: 3rem; padding-bottom: 2rem; border-bottom: 1px solid #e5e7eb; }
    .section h2 { color: var(--primary); }
    .subtitle { color: #6b7280; font-size: 1.1rem; }
    .cta { display: inline-block; background: var(--primary); color: #fff; padding: .6rem 1.4rem; border-radius: 6px; text-decoration: none; margin-top: .5rem; }
    dl { display: grid; gap: 1rem; }
    dt { font-weight: 600; }
    dd { margin: 0; color: #374151; }
    blockquote { background: #f9fafb; border-left: 4px solid var(--primary); padding: 1rem 1.25rem; margin: 0 0 1rem; border-radius: 0 6px 6px 0; }
    blockquote footer { font-size: .85rem; color: #6b7280; margin-top: .5rem; }
    footer { background: #111827; color: #9ca3af; text-align: center; padding: 1.5rem; font-size: .85rem; }
  </style>
</head>
<body>
  <header>
    ${tenant.logoUrl ? `<img src="../assets/logo${tenant.logoUrl.match(/\.\w+$/)?.[0] || '.png'}" alt="${escapeHtml(tenant.universityName)}" style="height:40px;margin-bottom:.5rem;display:block;">` : ''}
    <h1>${escapeHtml(tenant.universityName)} — ${langName}</h1>
  </header>
  <main>
    ${sectionHtml || '<p>No sections enabled.</p>'}
    ${faqHtml ? `<section class="section"><h2>FAQ</h2><dl>${faqHtml}</dl></section>` : ''}
    ${testimonialHtml ? `<section class="section"><h2>Testimonials</h2>${testimonialHtml}</section>` : ''}
  </main>
  <footer>
    <p>&copy; ${new Date().getFullYear()} ${escapeHtml(tenant.universityName)}. Generated by University Landing Platform.</p>
  </footer>
</body>
</html>`;
}

export async function buildSiteZip(tenantId: string): Promise<Buffer> {
  const [tenant, theme, sectionsList, faqList, testimonialsList, seo] = await Promise.all([
    storage.getTenant(tenantId),
    storage.getTheme(tenantId),
    storage.getSections(tenantId),
    storage.getFaqItems(tenantId),
    storage.getTestimonials(tenantId),
    storage.getSeoSettings(tenantId),
  ]);

  if (!tenant) throw new Error('Tenant not found');

  const zip = new JSZip();
  const langFolder = zip.folder('pages')!;

  for (const lang of SUPPORTED_LANGUAGES as readonly SupportedLanguage[]) {
    const html = renderLangPage(lang, tenant, theme, sectionsList, faqList, testimonialsList, seo);
    langFolder.file(`${lang}/index.html`, html);
  }

  // Root index.html that redirects to EN
  zip.file('index.html', `<!DOCTYPE html>
<html><head><meta http-equiv="refresh" content="0; url=pages/en/index.html">
<title>${escapeHtml(tenant.universityName)}</title></head>
<body><a href="pages/en/index.html">Enter site</a></body></html>`);

  // Manifest
  zip.file('manifest.json', JSON.stringify({
    exportedAt: new Date().toISOString(),
    universityName: tenant.universityName,
    domain: tenant.domain,
    languages: [...SUPPORTED_LANGUAGES],
    sections: sectionsList.filter(s => s.isEnabled).map(s => s.sectionKey),
  }, null, 2));

  return zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', compressionOptions: { level: 6 } });
}

export async function captureSnapshot(tenantId: string): Promise<Record<string, any>> {
  const [tenant, theme, sectionsList, faqList, testimonialsList, seo, domains] = await Promise.all([
    storage.getTenant(tenantId),
    storage.getTheme(tenantId),
    storage.getSections(tenantId),
    storage.getFaqItems(tenantId),
    storage.getTestimonials(tenantId),
    storage.getSeoSettings(tenantId),
    storage.getTenantDomains(tenantId),
  ]);

  return { tenant, theme, sections: sectionsList, faqItems: faqList, testimonials: testimonialsList, seoSettings: seo, domains, capturedAt: new Date().toISOString() };
}

export async function restoreSnapshot(tenantId: string, snapshot: Record<string, any>): Promise<void> {
  const { tenant, theme, sections: snapshotSections, faqItems: snapshotFaq, testimonials: snapshotTestimonials, seoSettings: snapshotSeo } = snapshot;

  if (tenant) {
    const { id, createdAt, ...tenantData } = tenant;
    await storage.updateTenant(tenantId, tenantData);
  }
  if (theme) {
    const { id, tenantId: _t, ...themeData } = theme;
    const existing = await storage.getTheme(tenantId);
    if (existing) await storage.updateTheme(tenantId, themeData);
    else await storage.createTheme({ tenantId, ...themeData });
  }
  if (snapshotSeo) {
    const { id, tenantId: _t, ...seoData } = snapshotSeo;
    const existing = await storage.getSeoSettings(tenantId);
    if (existing) await storage.updateSeoSettings(tenantId, seoData);
    else await storage.createSeoSettings({ tenantId, ...seoData });
  }
  if (Array.isArray(snapshotSections)) {
    for (const s of snapshotSections) {
      const { id, tenantId: _t, ...sData } = s;
      await storage.updateSection(id, sData).catch(() => {});
    }
  }
  if (Array.isArray(snapshotFaq)) {
    for (const f of snapshotFaq) {
      const { id, tenantId: _t, ...fData } = f;
      await storage.updateFaqItem(id, fData).catch(() => {});
    }
  }
  if (Array.isArray(snapshotTestimonials)) {
    for (const t of snapshotTestimonials) {
      const { id, tenantId: _t, ...tData } = t;
      await storage.updateTestimonial(id, tData).catch(() => {});
    }
  }
}
